"""GUPPI futzer skill CLI."""

import subprocess
from pathlib import Path
from typing import Annotated

import typer

from guppi_futzer import __version__
from guppi_futzer.config import (
    CONFIG_DIR,
    CONFIG_FILE,
    ensure_config,
    resolve_profile,
)
from guppi_futzer.modules import zsh


def _version_callback(value: bool):
    if value:
        typer.echo(f"guppi-futzer {__version__}")
        raise typer.Exit()


app = typer.Typer(help="Opinionated config generator you own and understand")


@app.callback()
def main(
    version: Annotated[bool, typer.Option("--version", "-V", help="Show version and exit", callback=_version_callback, is_eager=True)] = False,
):
    pass
generate_app = typer.Typer(help="Generate config files")
app.add_typer(generate_app, name="generate")


# --- Generate commands ---


@generate_app.command("zsh")
def generate_zsh(
    profile: Annotated[
        str | None,
        typer.Option("--profile", "-p", help="Profile name (default: $FUTZER_PROFILE or 'default')"),
    ] = None,
    output: Annotated[
        Path | None,
        typer.Option("--output", "-o", help="Write to file instead of stdout"),
    ] = None,
):
    """Generate opinionated zsh config."""
    resolved = resolve_profile(profile)
    content = zsh.generate(terminal=resolved.terminal)

    if output:
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(content)
        typer.echo(f"Written to {output}")
    else:
        typer.echo(content, nl=False)


# --- Apply command ---

SOURCE_LINE = '[[ -f ~/.config/guppi/futzer/init.zsh ]] && source ~/.config/guppi/futzer/init.zsh'


@app.command()
def apply(
    profile: Annotated[
        str | None,
        typer.Option("--profile", "-p", help="Profile name (default: $FUTZER_PROFILE or 'default')"),
    ] = None,
):
    """Generate all configs to ~/.config/guppi/futzer/ and wire into .zshrc."""
    resolved = resolve_profile(profile)

    # Ensure config.toml exists
    ensure_config()

    # Generate zsh.zsh
    zsh_content = zsh.generate(terminal=resolved.terminal)
    zsh_path = CONFIG_DIR / "zsh.zsh"
    zsh_path.write_text(zsh_content)
    typer.echo(f"  Generated {zsh_path}")

    # Generate init.zsh
    init_content = _generate_init()
    init_path = CONFIG_DIR / "init.zsh"
    init_path.write_text(init_content)
    typer.echo(f"  Generated {init_path}")

    # Wire into .zshrc
    zshrc = Path.home() / ".zshrc"
    if zshrc.exists():
        zshrc_content = zshrc.read_text()
        if SOURCE_LINE not in zshrc_content:
            with zshrc.open("a") as f:
                f.write(f"\n# futzer — opinionated shell config\n{SOURCE_LINE}\n")
            typer.echo(f"  Added source line to {zshrc}")
        else:
            typer.echo(f"  {zshrc} already sources futzer")
    else:
        zshrc.write_text(f"# futzer — opinionated shell config\n{SOURCE_LINE}\n")
        typer.echo(f"  Created {zshrc}")

    typer.echo(f"\nProfile: {resolved.name} (terminal: {resolved.terminal})")
    typer.echo("Run 'source ~/.config/guppi/futzer/init.zsh' to activate in this shell.")


def _generate_init() -> str:
    """Generate init.zsh that sources all enabled modules."""
    return """\
# futzer init — sources all enabled modules
# Generated by guppi-futzer. Do not edit directly.

FUTZER_DIR="${0:A:h}"

# Core zsh config
[[ -f "$FUTZER_DIR/zsh.zsh" ]] && source "$FUTZER_DIR/zsh.zsh"
"""


# --- Status command ---


@app.command()
def status():
    """Show active profile, generated files, and .zshrc integration."""
    resolved = resolve_profile()

    typer.echo(f"Profile: {resolved.name} (terminal: {resolved.terminal})")
    typer.echo(f"Config:  {CONFIG_FILE} ({'exists' if CONFIG_FILE.exists() else 'not found'})")
    typer.echo()

    # Check generated files
    typer.echo("Generated files:")
    for name in ["init.zsh", "zsh.zsh"]:
        path = CONFIG_DIR / name
        status = "exists" if path.exists() else "not generated"
        typer.echo(f"  {path} ({status})")

    # Check .zshrc
    typer.echo()
    zshrc = Path.home() / ".zshrc"
    if zshrc.exists() and SOURCE_LINE in zshrc.read_text():
        typer.echo(".zshrc: sources futzer")
    else:
        typer.echo(".zshrc: does NOT source futzer (run 'guppi-futzer apply')")


# --- Skill management subcommand group ---

skill_app = typer.Typer(help="Skill management commands")
app.add_typer(skill_app, name="skill")


@skill_app.command()
def install():
    """Register this skill with guppi-cli."""
    skill_md = _get_skill_md_path()
    skill_dir = skill_md.parent
    result = subprocess.run(
        ["guppi", "skills", "install", "futzer", "--from", str(skill_dir), "--yes"],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        typer.echo(result.stdout.strip())
    else:
        typer.echo(f"Error: {result.stderr.strip()}", err=True)
        raise typer.Exit(1)


@skill_app.command()
def show():
    """Display SKILL.md contents."""
    skill_md = _get_skill_md_path()
    typer.echo(skill_md.read_text())


def _get_skill_md_path() -> Path:
    """Locate SKILL.md bundled in the package."""
    package_dir = Path(__file__).parent
    skill_md = package_dir / "SKILL.md"
    if not skill_md.exists():
        skill_md = package_dir.parent.parent / "SKILL.md"
    if not skill_md.exists():
        typer.echo("Error: SKILL.md not found", err=True)
        raise typer.Exit(1)
    return skill_md


if __name__ == "__main__":
    app()
