"""ZSH module — generates opinionated zsh configuration."""


def generate(terminal: str = "ghostty") -> str:
    """Generate a complete opinionated zsh config.

    Args:
        terminal: Terminal emulator name (ghostty, iterm2). Affects
                  advisory comments but not keybindings (they're universal).
    """
    sections = [
        _header(terminal),
        _completion(),
        _history(),
        _options(),
        _vi_mode(),
        _keybindings(),
        _prompt(),
    ]
    return "\n".join(sections)


def _header(terminal: str) -> str:
    return f"""\
# futzer zsh config — generated by guppi-futzer
# Terminal: {terminal}
# Do not edit directly. Regenerate with: guppi-futzer generate zsh
"""


def _completion() -> str:
    return """\
# --- Completion ---
autoload -Uz compinit && compinit

# Case-insensitive, partial-word, and substring completion
# Example: "cd zsh<Tab>" matches "2026-02-26-zsh"
zstyle ':completion:*' matcher-list \\
  'm:{[:lower:][:upper:]}={[:upper:][:lower:]}' \\
  'r:|=*' \\
  'l:|=* r:|=*'

# Arrow-key driven menu selection
zstyle ':completion:*:*:*:*:*' menu select

# Complete . and .. directories
zstyle ':completion:*' special-dirs true

# Colorize completion list
zstyle ':completion:*' list-colors ''
"""


def _history() -> str:
    return """\
# --- History ---
HISTFILE=~/.zsh_history
HISTSIZE=50000
SAVEHIST=50000

setopt SHARE_HISTORY          # Share history across all sessions
setopt INC_APPEND_HISTORY     # Write immediately, not on shell exit
setopt HIST_IGNORE_DUPS       # Skip consecutive duplicates
setopt HIST_IGNORE_ALL_DUPS   # Remove older duplicate from history
setopt HIST_FIND_NO_DUPS      # Don't show duplicates when searching
setopt HIST_REDUCE_BLANKS     # Trim unnecessary whitespace
setopt HIST_VERIFY            # Show expanded history before executing
"""


def _options() -> str:
    return """\
# --- Options ---
setopt AUTO_CD                # "dirname" is equivalent to "cd dirname"
setopt AUTO_PUSHD             # cd pushes old dir onto stack
setopt PUSHD_IGNORE_DUPS      # Don't push duplicate dirs
setopt INTERACTIVE_COMMENTS   # Allow # comments in interactive shell
setopt EXTENDED_GLOB          # Enable extended glob patterns (#, ~, ^)
setopt NO_BEEP                # Silence terminal bell
"""


def _vi_mode() -> str:
    return """\
# --- Vi Mode ---
bindkey -v
export KEYTIMEOUT=1           # 10ms delay for key sequences (snappy mode switch)

# Cursor shape: block for normal mode, beam for insert mode
function zle-keymap-select {
  case $KEYMAP in
    vicmd)      echo -ne '\\e[2 q' ;;  # block
    viins|main) echo -ne '\\e[6 q' ;;  # beam
  esac
}
zle -N zle-keymap-select

function zle-line-init {
  echo -ne '\\e[6 q'                    # beam on new prompt
}
zle -N zle-line-init
"""


def _keybindings() -> str:
    return """\
# --- Keybindings ---
# These work across Ghostty, iTerm2, and most xterm-compatible terminals.
# Note: For Option+Arrow in iTerm2, set "Left Option Key" to "Esc+"
#       in Preferences > Profiles > Keys.

# Ctrl+Arrow: word movement
bindkey '\\e[1;5D' backward-word       # Ctrl+Left
bindkey '\\e[1;5C' forward-word        # Ctrl+Right

# Option+Arrow: word movement (macOS)
bindkey '\\eb'     backward-word       # Option+Left (ESC+b)
bindkey '\\ef'     forward-word        # Option+Right (ESC+f)
bindkey '\\e[1;3D' backward-word       # Alt+Left (standard CSI)
bindkey '\\e[1;3C' forward-word        # Alt+Right (standard CSI)

# Home / End
bindkey '\\eOH' beginning-of-line      # Home (application mode)
bindkey '\\e[H' beginning-of-line      # Home (normal mode)
bindkey '\\eOF' end-of-line            # End (application mode)
bindkey '\\e[F' end-of-line            # End (normal mode)

# Delete
bindkey '\\e[3~' delete-char           # Forward delete

# Vi-mode overrides: keep Ctrl+A/E working in insert mode
bindkey -M viins '^A' beginning-of-line
bindkey -M viins '^E' end-of-line
bindkey -M viins '^K' kill-line
bindkey -M viins '^U' backward-kill-line
bindkey -M viins '^W' backward-kill-word
bindkey -M viins '^Y' yank
"""


def _prompt() -> str:
    return """\
# --- Prompt ---
# Minimal prompt using vcs_info (built into zsh, no external deps)
autoload -Uz vcs_info
precmd() { vcs_info }

zstyle ':vcs_info:git:*' formats ' %F{green}%b%f'
zstyle ':vcs_info:git:*' actionformats ' %F{green}%b%f %F{red}(%a)%f'
zstyle ':vcs_info:*' enable git

setopt PROMPT_SUBST
PROMPT='%F{blue}%~%f${vcs_info_msg_0_} %# '
"""
